name: 'Install Tools'
# This GitHub Action installs development tools based on OS and user input.
description: 'Installs task, opentofu, and uv.'
author: 'Eric Veenendaal'

inputs:
  include:
    description: 'Comma-separated list of tools to include (e.g., task,opentofu,uv). If empty, all tools are installed.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # =====================
    # macOS Installation
    # =====================
    - name: Install go-task on macOS
      # Installs go-task using Homebrew if included or if no tools specified
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'task'))
      shell: bash
      run: brew install go-task
    - name: Install opentofu on macOS
      # Installs opentofu using Homebrew if included or if no tools specified
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'opentofu'))
      shell: bash
      run: brew install opentofu
    - name: Install uv on macOS
      # Installs uv using Homebrew if included or if no tools specified
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'uv'))
      shell: bash
      run: brew install uv
    # =====================
    # Linux Installation
    # =====================
    - name: Install go-task on Linux
      # Installs go-task using snap if included or if no tools specified
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'task'))
      shell: bash
      run: |
        if command -v snap &> /dev/null; then
          sudo snap install task --classic
        else
          echo "snap is not installed. Please install snap to use this action for task."
          exit 1
        fi
    - name: Install opentofu on Linux
      # Installs opentofu using snap if included or if no tools specified
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'opentofu'))
      shell: bash
      run: |
        if command -v snap &> /dev/null; then
          sudo snap install opentofu --classic
        else
          echo "snap is not installed. Please install snap to use this action for opentofu."
          exit 1
        fi
    - name: Install uv on Linux
      # Installs uv using pip if included or if no tools specified
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'uv'))
      shell: bash
      run: pip install uv

branding:
  icon: 'package'
  color: 'blue'
