name: 'Install Tools'
description: 'Installs task via pip and opentofu.'
author: 'Eric Veenendaal'

inputs:
  include:
    description: 'Comma-separated list of tools to include (e.g., task,opentofu). If empty, all tools are installed.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install task via pip
      shell: bash
      run: |
        if [[ -z "${{ inputs.include }}" || ",${{ inputs.include }}," == *",task,"* ]]; then
          pip install go-task-bin
        else
          echo "Skipping task installation."
        fi
    - name: Install OpenTofu
      shell: bash
      run: |
        if [[ -z "${{ inputs.include }}" || ",${{ inputs.include }}," == *",opentofu,"* ]]; then
          curl -sSL https://get.opentofu.org/install.sh | bash
        else
          echo "Skipping OpenTofu installation."
        fi

branding:
  icon: 'package'
  color: 'blue'
