name: 'Install Tools'
description: 'Installs task via pip and opentofu.'
author: 'Eric Veenendaal'

inputs:
  include:
    description: 'Comma-separated list of tools to include (e.g., task,opentofu). If empty, all tools are installed.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install task
      shell: bash
      run: |
        if [[ -z "${{ inputs.include }}" || ",${{ inputs.include }}," == *",task,"* ]]; then
          if [[ "$(uname)" == "Darwin" ]]; then
            pip install go-task-bin
          elif [[ "$(uname)" == "Linux" ]]; then
            if command -v snap &> /dev/null; then
              sudo snap install task --classic
            else
              echo "snap is not installed. Please install snap to use this action for task."
              exit 1
            fi
          else
            echo "Unsupported OS for task installation."
            exit 1
          fi
        else
          echo "Skipping task installation."
        fi
    - name: Install OpenTofu via snap
      shell: bash
      run: |
        if [[ -z "${{ inputs.include }}" || ",${{ inputs.include }}," == *",opentofu,"* ]]; then
          if command -v snap &> /dev/null; then
            sudo snap install opentofu --classic
          else
            echo "snap is not installed. Please install snap to use this action for opentofu."
            exit 1
          fi
        else
          echo "Skipping OpenTofu installation."
        fi

branding:
  icon: 'package'
  color: 'blue'
