name: 'Install Tools'
# This GitHub Action installs development tools based on OS and user input.
description: 'Installs task, opentofu, and uv.'
author: 'Eric Veenendaal'

inputs:
  include:
    description: 'Comma-separated list of tools to include (e.g., task,opentofu,uv). If empty, all tools are installed.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # =====================
    # macOS Installation
    # =====================
    - name: Install go-task on macOS
      # Installs go-task using Homebrew if 'task' is included
      if: runner.os == 'macOS' && inputs.include != '' && contains(inputs.include, 'task')
      shell: bash
      run: brew install go-task
    - name: Install opentofu on macOS
      # Installs opentofu using Homebrew if 'opentofu' is included
      if: runner.os == 'macOS' && inputs.include != '' && contains(inputs.include, 'opentofu')
      shell: bash
      run: brew install opentofu
    - name: Install uv on macOS
      # Installs uv using Homebrew if 'uv' is included
      if: runner.os == 'macOS' && inputs.include != '' && contains(inputs.include, 'uv')
      shell: bash
      run: brew install uv
    - name: Install fnm and Node 20 on macOS
      # Installs fnm (Fast Node Manager) and Node.js v20 if 'node20' is included
      if: runner.os == 'macOS' && inputs.include != '' && contains(inputs.include, 'node20')
      shell: bash
      run: |
        brew install fnm
        fnm install 20
        fnm use 20
        fnm default 20
    - name: Install fnm and Node 22 on macOS
      # Installs fnm (Fast Node Manager) and Node.js v22 if 'node22' is included
      if: runner.os == 'macOS' && inputs.include != '' && contains(inputs.include, 'node22')
      shell: bash
      run: |
        brew install fnm
        fnm install 22
        fnm use 22
        fnm default 22
    # =====================
    # Linux Installation
    # =====================
    - name: Install go-task on Linux
      # Installs go-task using snap if 'task' is included
      if: runner.os == 'Linux' && inputs.include != '' && contains(inputs.include, 'task')
      shell: bash
      run: |
        if command -v snap &> /dev/null; then
          sudo snap install task --classic
        else
          echo "snap is not installed. Please install snap to use this action for task."
          exit 1
        fi
    - name: Install opentofu on Linux
      # Installs opentofu using snap if 'opentofu' is included
      if: runner.os == 'Linux' && inputs.include != '' && contains(inputs.include, 'opentofu')
      shell: bash
      run: |
        if command -v snap &> /dev/null; then
          sudo snap install opentofu --classic
        else
          echo "snap is not installed. Please install snap to use this action for opentofu."
          exit 1
        fi
    - name: Install uv on Linux
      # Installs uv using pip if 'uv' is included
      if: runner.os == 'Linux' && inputs.include != '' && contains(inputs.include, 'uv')
      shell: bash
      run: pip install uv
    - name: Install fnm and Node 20 on Linux
      # Installs fnm (Fast Node Manager) and Node.js v20 if 'node20' is included
      if: runner.os == 'Linux' && inputs.include != '' && contains(inputs.include, 'node20')
      shell: bash
      run: |
        curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
        export PATH="$HOME/.local/share:$PATH"
        fnm install 20
        fnm use 20
        fnm default 20
    - name: Install fnm and Node 22 on Linux
      # Installs fnm (Fast Node Manager) and Node.js v22 if 'node22' is included
      if: runner.os == 'Linux' && inputs.include != '' && contains(inputs.include, 'node22')
      shell: bash
      run: |
        curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
        export PATH="$HOME/.local/share:$PATH"
        fnm install 22
        fnm use 22
        fnm default 22

branding:
  icon: 'package'
  color: 'blue'
