name: 'Install Tools'
description: 'Installs task via pip and opentofu.'
author: 'Eric Veenendaal'

inputs:
  include:
    description: 'Comma-separated list of tools to include (e.g., task,opentofu). If empty, all tools are installed.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install go-task on macOS
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'task'))
      shell: bash
      run: brew install go-task
    - name: Install opentofu on macOS
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'opentofu'))
      shell: bash
      run: brew install opentofu
    - name: Install uv on macOS
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'uv'))
      shell: bash
      run: brew install uv
    - name: Install go-task on Linux
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'task'))
      shell: bash
      run: |
        if command -v snap &> /dev/null; then
          sudo snap install task --classic
        else
          echo "snap is not installed. Please install snap to use this action for task."
          exit 1
        fi
    - name: Install opentofu on Linux
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'opentofu'))
      shell: bash
      run: |
        if command -v snap &> /dev/null; then
          sudo snap install opentofu --classic
        else
          echo "snap is not installed. Please install snap to use this action for opentofu."
          exit 1
        fi
    - name: Install uv on Linux
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'uv'))
      shell: bash
      run: pip install uv

branding:
  icon: 'package'
  color: 'blue'
