name: 'Install Tools'
description: 'Installs task via pip and opentofu.'
author: 'Eric Veenendaal'

inputs:
  exclude:
    description: 'Comma-separated list of tools to exclude (e.g., task,opentofu)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install task via pip
      shell: bash
      run: |
        if [[ ",${{ inputs.exclude }}," != *",task,"* ]]; then
          pip install go-task-bin
        else
          echo "Skipping task installation."
        fi
    - name: Install OpenTofu
      shell: bash
      run: |
        if [[ ",${{ inputs.exclude }}," != *",opentofu,"* ]]; then
          curl -sSL https://get.opentofu.org/install.sh | bash
        else
          echo "Skipping OpenTofu installation."
        fi

branding:
  icon: 'package'
  color: 'blue'
