name: 'Install Tools'
description: 'Installs task via pip and opentofu.'
author: 'Eric Veenendaal'

inputs:
  include:
    description: 'Comma-separated list of tools to include (e.g., task,opentofu). If empty, all tools are installed.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install tools
      shell: bash
      run: |
        # Helper to check if a tool is included
        included() {
          [[ -z "${{ inputs.include }}" || ",${{ inputs.include }}," == *",$1,"*" ]]
        }
        if [[ "$(uname)" == "Darwin" ]]; then
          if included task; then
            brew install go-task
          else
            echo "Skipping task installation."
          fi
          if included opentofu; then
            brew install opentofu
          else
            echo "Skipping OpenTofu installation."
          fi
          if included uv; then
            brew install uv
          else
            echo "Skipping uv installation."
          fi
        elif [[ "$(uname)" == "Linux" ]]; then
          if included task; then
            if command -v snap &> /dev/null; then
              sudo snap install task --classic
            else
              echo "snap is not installed. Please install snap to use this action for task."
              exit 1
            fi
          else
            echo "Skipping task installation."
          fi
          if included opentofu; then
            if command -v snap &> /dev/null; then
              sudo snap install opentofu --classic
            else
              echo "snap is not installed. Please install snap to use this action for opentofu."
              exit 1
            fi
          else
            echo "Skipping OpenTofu installation."
          fi
          if included uv; then
            pip install uv
          else
            echo "Skipping uv installation."
          fi
        else
          echo "Unsupported OS for tool installation."
          exit 1
        fi

branding:
  icon: 'package'
  color: 'blue'
