name: 'Install Tools'
# This GitHub Action installs development tools based on OS and user input.
description: 'Installs task, opentofu, uv, age, and plantuml.'
author: 'Eric Veenendaal'

inputs:
  include:
    description: 'Comma-separated list of tools to include (e.g., task,opentofu,uv,age,plantuml). If empty, all tools are installed.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # =====================
    # macOS Installation
    # =====================
    - name: Install go-task on macOS
      # Installs go-task using Homebrew if 'task' is included or if include is empty
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'task'))
      shell: bash
      run: |
        brew install go-task
        brew link --overwrite --force go-task
    - name: Install opentofu on macOS
      # Installs opentofu using Homebrew if 'opentofu' is included or if include is empty
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'opentofu'))
      shell: bash
      run: |
        brew install opentofu
        brew link --overwrite --force opentofu
    - name: Install uv on macOS
      # Installs uv using Homebrew if 'uv' is included or if include is empty
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'uv'))
      shell: bash
      run: |
        brew install uv
        brew link --overwrite --force uv
    - name: Install age on macOS
      # Installs age using Homebrew if 'age' is included or if include is empty
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'age'))
      shell: bash
      run: |
        brew install age
        brew link --overwrite --force age
    - name: Install plantuml on macOS
      # Installs plantuml using Homebrew if 'plantuml' is included or if include is empty
      if: runner.os == 'macOS' && (inputs.include == '' || contains(inputs.include, 'plantuml'))
      shell: bash
      run: |
        brew install plantuml
        brew link --overwrite --force plantuml

    # =====================
    # Linux Installation
    # =====================
    - name: Install Homebrew on Linux
      # Installs Homebrew if any tools are requested on Linux
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'task') || contains(inputs.include, 'opentofu') || contains(inputs.include, 'uv') || contains(inputs.include, 'age') || contains(inputs.include, 'plantuml'))
      shell: bash
      run: |
        if ! command -v brew &> /dev/null; then
          # Suppress ldd broken pipe errors by redirecting stderr
          HOMEBREW_NO_ENV_HINTS=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 2>&1 | grep -v "printf: write error"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          # Add Homebrew directories to PATH for subsequent workflow steps
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
          # Install build dependencies
          sudo apt-get update -qq
          sudo apt-get install -y -qq build-essential
        fi
    - name: Install go-task on Linux
      # Installs go-task using Homebrew if 'task' is included or if include is empty
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'task'))
      shell: bash
      env:
        HOMEBREW_NO_ENV_HINTS: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install go-task
        brew link --overwrite --force go-task
    - name: Install opentofu on Linux
      # Installs opentofu using Homebrew if 'opentofu' is included or if include is empty
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'opentofu'))
      shell: bash
      env:
        HOMEBREW_NO_ENV_HINTS: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install opentofu
        brew link --overwrite --force opentofu
    - name: Install uv on Linux
      # Installs uv using Homebrew if 'uv' is included or if include is empty
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'uv'))
      shell: bash
      env:
        HOMEBREW_NO_ENV_HINTS: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install uv
        brew link --overwrite --force uv
    - name: Install age on Linux
      # Installs age using Homebrew if 'age' is included or if include is empty
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'age'))
      shell: bash
      env:
        HOMEBREW_NO_ENV_HINTS: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install age
        brew link --overwrite --force age
    - name: Install plantuml on Linux
      # Installs plantuml using Homebrew if 'plantuml' is included or if include is empty
      if: runner.os == 'Linux' && (inputs.include == '' || contains(inputs.include, 'plantuml'))
      shell: bash
      env:
        HOMEBREW_NO_ENV_HINTS: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install plantuml
        brew link --overwrite --force plantuml

branding:
  icon: 'package'
  color: 'blue'
